### ISSUE TITLE
Clarification about what is meant by not manipulating the HTML

### ISSUE THREAD

**Issue by gemmaelsom** [jvitale/une_ICT100_assignment4#3]
I get that the intent with the comment about us not manipulating the HTML directly is meant to prevent us from manually moving the shapes around using javascript, but it wasn't clear to me that attaching events to the HTML for things like 'click' were ok.

Can we add that clarification somewhere, I'm sure there's a student who is trying to subscribe to a click event from the game controller because this constraint wasn't defined tightly.

**Comment by jvitale** [comment]
I added a note about the use of getElementById to access buttons and text boxes in line with what you suggested.
